apiVersion: v1
kind: Secret
metadata:
  name: timescale-dsn
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  CONNECTION_STRING: |
    {{- /* DSN priority: explicit values.timescale.dsn, then computed when install=true */ -}}
    {{- $explicit := .Values.timescale.dsn | default "" -}}
    {{- $install := .Values.timescale.install | default false -}}
    {{- $user := .Values.timescale.user | default "karman" -}}
    {{- $pass := .Values.timescale.password | default "karman" -}}
    {{- $db   := .Values.timescale.database | default "karman" -}}
    {{- $host := printf "timescale.%s.svc" .Values.namespace -}}
    {{- $port := .Values.timescale.port | default 5432 -}}
    {{- $computed := printf "postgres://%s:%s@%s:%v/%s?sslmode=disable" $user $pass $host $port $db -}}
    {{- if $explicit }}
    {{ $explicit }}
    {{- else if $install }}
    {{ $computed }}
    {{- else }}
    {{ "" }}
    {{- end }}
